name: Build and Push Docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV
    permissions:
      contents: read
      packages: write
    env:
      NODE_ENV: ${{vars.NODE_ENV || 'production'}}
      APP_NAME: ${{vars.APP_NAME || 'QHunt App'}}
      APP_API_URL: ${{vars.APP_API_URL || '/'}}
      APP_SOCKET_URL: ${{vars.APP_SOCKET_URL || '/'}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
          registry: ghcr.io

      - name: Build and push Docker
        uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            NODE_ENV=${{ env.NODE_ENV }}
            APP_NAME=${{ env.APP_NAME }}
            APP_API_URL=${{ env.APP_API_URL }}
            APP_SOCKET_URL=${{ env.APP_SOCKET_URL }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/qhunt-app:latest
            ghcr.io/${{ github.repository_owner }}/qhunt-app:${{ github.sha }}
          outputs: |
            type=image,name=target,annotation-index.org.opencontainers.image.description=QHunt App Image
          push: true
